### ISSUE TITLE
Replace spaces with underscore (or dash)

### ISSUE THREAD

**Issue by danielk-sn** [rickstaa/action-create-tag#22]
When specifying a string that contains spaces, the tag will fail.
Would be nice to replace strings with dashes or underscore

**Comment by rickstaa** [comment]
@danielk-sn Thanks for your feature request. I think your proposal makes sense! 👍🏻 Feel free to create a PR. I believe the following syntax can replace the spaces (see https://stackoverflow.com/questions/19661267/replace-spaces-with-underscores-via-bash).

```bash
${INPUT_TAG/ /_}
```

I think the important thing is that people can change the delimited to a dash using an action parameter if they like.

**Comment by rickstaa** [comment]
@danielk-sn You feature request was implemented in #25 and released in https://github.com/rickstaa/action-create-tag/releases/tag/v1.4.0.
