### ISSUE TITLE
Support for Windows and Mac

### ISSUE THREAD

**Issue by Gakk** [rickstaa/action-create-tag#26]
**Is your feature request related to a problem? Please describe.**

Running this on a Windows and Mac is not supported:
![image](https://user-images.githubusercontent.com/5013909/203818984-4d0d5fab-da92-49d3-afa6-407523831ffe.png)

**Describe the solution you'd like**

Either support Windows and Mac or document on [readme](https://github.com/rickstaa/action-create-tag/blob/main/README.md) that this action only supports Linux.

**Describe alternatives you've considered**
The current alternative is to find another Github action to use 😇

**Comment by rickstaa** [comment]
@Gakk (and @ismael-gobernado-deltatre) This is a limitation that is present in the current Github docker actions (see the [Github action documentation](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action)). I can, however, easily add Windows and Mac support by converting this action into [a composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action). What do you think?

I have more pressing deadlines before the new year, but I can release this composite version on https://github.com/rickstaa/action-create-tag-composite somewhere at the start of the new year. 🚀

**Comment by Gakk** [comment]
Thanks for your response @rickstaa.

Instead of using an action I went with just using the GIT command line:

```
    - name: Tag published version
      run: |
        git tag -a v${{ needs.build.outputs.versionTag }} -m "Published version ${{ needs.build.outputs.versionTag }}" ${GITHUB_SHA}
        git push origin v${{ needs.build.outputs.versionTag }}
```

If you would like to convert your action into a composite action that is up to you, and thank you for being willing to do so, but I think I will keep using the simple command anyway now that it is implemented.

**Comment by rickstaa** [comment]
> Thanks for your response @rickstaa.
> 
> Instead of using an action I went with just using the GIT command line:
> 
> ```
>     - name: Tag published version
>       run: |
>         git tag -a v${{ needs.build.outputs.versionTag }} -m "Published version ${{ needs.build.outputs.versionTag }}" ${GITHUB_SHA}
>         git push origin v${{ needs.build.outputs.versionTag }}
> ```
> 
> If you would like to convert your action into a composite action, that is up to you, and thank you for being willing to do so, but I think I will keep using the simple command anyway now that it is implemented.

Thanks for letting me know! Yea, the command line is the best way I have used it myself in some projects. Maybe I will document this option instead of creating a composite action. 🤔 If it's okay with you, I would like to keep this issue open for a bit so that I don't forget. 👍🏻

**Comment by Gakk** [comment]
> If it's okay with you, I would like to keep this issue open for a bit so that I don't forget. 👍🏻

Please keep it open until documented 🙂👍

**Comment by rickstaa** [comment]
@Gakk I documented this in https://github.com/rickstaa/action-create-tag/releases/tag/v1.5.4 as I currently do not have the time to create a branch with a composite version of this action. If somebody wants to take this on in the future, feel free to create a PR. 👍🏻
