### ISSUE TITLE
Input to indicate if the tag exists skip creation process

### ISSUE THREAD

**Issue by codebydant** [rickstaa/action-create-tag#30]
**Is your feature request related to a problem? Please describe.**
We have 2 options regarding existing tags. Overwrite or raise an error if the tag exists

**Describe the solution you'd like**
An input to validate if the tag exists skips the creation process and proceeds to the next job in the workflow. This can be used to avoid the dangerous option of overwriting a tag and still we will have a successful execution on the job.

**Describe alternatives you've considered**
Move the create tag job at the end of my workflow (is not the perfect solution)

**Additional context**

**Comment by rickstaa** [comment]
@dtcMLOps I like it. I, unfortunately, currently don't have time to implement this. Feel free to create a PR, and I will review it 👍🏻. Otherwise, I will leave this issue open as a feature request.

**Comment by rickstaa** [comment]
> I have found an action with this feature already implemented. I will leave it here for future reference:
> 
> https://github.com/joutvhu/create-tag
> 
> Thanks!

Since this feature was straightforward to implement, and I could use it in some of my repositories, I released it under https://github.com/rickstaa/action-create-tag/releases/tag/v1.6.0. You can choose which action you prefer 👍🏻.
