### ISSUE TITLE
cannot lock ref 'refs/tags': Filename too long

### ISSUE THREAD

**Issue by kroese** [rickstaa/action-create-tag#33]
Im getting the following error:

```
[action-create-tag] Create tag 'v***.***'.
fatal: cannot lock ref 'refs/tags/v***.***': Unable to create '/github/workspace/.git/refs/tags/v***.***.lock': Filename too long
```

The `Filename too long` part is very weird, since my tags are very short (5 characters) and the path in the message doesn't seem long at all.

Could there be something else that is causing this? For example, my master branch is protected to not accept push, only pull request. Does the tag creation require a push for example?

**Comment by rickstaa** [comment]
Great. Thanks for letting me know. Strange that it gives such a cryptic message 🤔.
