### ISSUE TITLE
Please add instructions on how to add the GitHub token for authohorization to the example

### ISSUE THREAD

**Issue by siloKalle** [rickstaa/action-create-tag#38]

**Comment by rickstaa** [comment]
@siloKalle thanks for your suggestion. Feel free to create a PR 👍🏻.

**Comment by sulejmanarifi** [comment]
Am I also missing something, providing github_token with full permissions, I still get 403 response..

**Comment by sulejmanarifi** [comment]
> Am I also missing something, providing github_token with full permissions, I still get 403 response..

Nvm, found the issue, it was caused due workflow had no permission for writing...

**Comment by siloKalle** [comment]
Actually, I had the same fault :D

**Comment by rickstaa** [comment]
Closing this as it looks like this is already fixed. As explained in the README the `github_token` is only needed when using `v1` of the checkout action (see https://github.com/rickstaa/action-create-tag?tab=readme-ov-file#github_token).
